### ISSUE TITLE
실험

### ISSUE THREAD

**Issue by DESECTORCON** [choeminjun/pythonwork#2]
New issue 시작!

**Comment by DESECTORCON** [comment]
정답 코드

**Comment by choeminjun** [comment]
![image](https://cloud.githubusercontent.com/assets/13284086/13371804/3c34ec48-dd72-11e5-8ce1-79a83cbda051.png)

**Comment by choeminjun** [comment]
![image](https://cloud.githubusercontent.com/assets/13284086/13371812/4cb598b0-dd72-11e5-92ae-904660c2e89d.png)

**Comment by DESECTORCON** [comment]
[code.zip](https://github.com/choeminjun/pythonwork/files/149254/code.zip)
[inventwithpython.zip](https://github.com/choeminjun/pythonwork/files/149255/inventwithpython.zip)
[makinggames.zip](https://github.com/choeminjun/pythonwork/files/149256/makinggames.zip)

정답들

**Comment by DESECTORCON** [comment]
아빠께...
아빠!
issue가 뭐예요??

**Comment by DESECTORCON** [comment]
정답코드(the bor...)
[Automate_the_Boring_Stuff_onlinematerials.zip](https://github.com/choeminjun/pythonwork/files/211638/Automate_the_Boring_Stuff_onlinematerials.zip)
