### ISSUE TITLE
아빠께

### ISSUE THREAD

**Issue by DESECTORCON** [choeminjun/pythonwork#5]
my_IDES 폴더를 봐 주세용~!

**Comment by DESECTORCON** [comment]
4/13에
업대이트 했습니당~!
꼭~! 봐 주세용~!

**Comment by DESECTORCON** [comment]
4/17에
업대이트 했습니당~!
꼭~! 봐 주세용~!

**Comment by choeminjun** [comment]
지금 s.e NOTE service 업대이트중 입니다.
